# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.acme.org:
  orderer3.acme.org:
  orderer4.acme.org:
  orderer5.acme.org:

networks:
  byfn:

services:

  orderer2.acme.org:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.acme.org
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/acme.org/orderers/orderer2.acme.org/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/acme.org/orderers/orderer2.acme.org/tls/:/var/hyperledger/orderer/tls
        - orderer2.acme.org:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.acme.org:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.acme.org
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/acme.org/orderers/orderer3.acme.org/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/acme.org/orderers/orderer3.acme.org/tls/:/var/hyperledger/orderer/tls
        - orderer3.acme.org:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  orderer4.acme.org:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer4.acme.org
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/acme.org/orderers/orderer4.acme.org/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/acme.org/orderers/orderer4.acme.org/tls/:/var/hyperledger/orderer/tls
        - orderer4.acme.org:/var/hyperledger/production/orderer
    ports:
    - 10050:7050

  orderer5.acme.org:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer5.acme.org
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/acme.org/orderers/orderer5.acme.org/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/acme.org/orderers/orderer5.acme.org/tls/:/var/hyperledger/orderer/tls
        - orderer5.acme.org:/var/hyperledger/production/orderer
    ports:
    - 11050:7050
